### ISSUE TITLE
First messages from Node are not populated instantly

### ISSUE THREAD

**Issue by carmilso** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-android#56]
Hi! The first messages like "Welcome back!" and "If you need help at any point, try ‘help’." are only populated in the RecyclerView when "onResume" method is executed after an "onPause" execution. 

e.g. You init the app, then go to "My goods" section and then return to the mainActivity. In that case the welcome messages are populated. It is as if It had no time to populate them.

If you use `SystemClock.sleep(3000);` at the end of "onCreate" method, then welcome messages are well populated since NodeJS has enough time to send them before the app is loaded, but this is an ugly workaround.

**Comment by gcampax** [comment]
It is actually intentional that the app shows up before the messages are there.
As you mention, NodeJS takes some time to start up (usually ~500ms to ~800ms, in my measurements).
If you wait for it to be ready the app appears to freeze, which is a worse UX.

You could maybe have the "I'm thinking" spinner (next to the cancel button) running while the app is loading. Or delay hiding the welcome screen. Not sure if that would be better.
