### ISSUE TITLE
Request: Add Almond Android to the F-Droid store

### ISSUE THREAD

**Issue by r0bbie** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-android#69]
Please consider submitting Almond to the [F-Droid](https://f-droid.org/) open source app store.

**Comment by gcampax** [comment]
Unfortunately, it seems that F-Droid prohibits apps from using Google Play Services. We use multiple Google Play Services libraries (for accessing user location, map widgets, and to use Google OAuth), and we don't have the manpower to investigate alternative libraries, even if they existed.

We will gladly accept a PR optionally removing the dependency though, provided it does not reduce functionality or increase the maintenance burden.

**Comment by r0bbie** [comment]
Ah, that's unfortunate. Hopeful for a divergence from reliance on proprietary Google Play Services in the future then.

(Nonetheless I'll watch the Almond project with interest / give it a go on other platforms in the meantime!)

**Comment by gary-host-laptop** [comment]
Do you still think it would be impossible to have an F-droid version? I think that you can still have the Google Store version with all the dependencies so that keeping track of everything is easier and a different one for F-droid. If not, maybe https://github.com/IzzySoft can add you to their repository which has a less strict criteria for app inclusion, but you can also download them from F-droid or Aurora Droid. I don't know how to mention a user here, I would do it if I could.
